### ISSUE TITLE
Saved Configurations not listed 

### ISSUE THREAD

**Issue by framemytv** [Frame-My-TV/app#154]
When you try to view the "My Saved Designs" from he left nav panel you just get this .... 

![155 1](https://cloud.githubusercontent.com/assets/16761791/13190430/203e1c28-d72b-11e5-9d5d-932259167f86.png)

**Comment by framemytv** [comment]
Still does not appear to work. All I see is the same screenshot shown in this initial ticket. I've tried in both Chrome and Safari and have cleared my cache.

**Comment by arendsokken** [comment]
Did you delete the cache on your browser?
After that, pls check again.
