### ISSUE TITLE
Packing slip page breaks

### ISSUE THREAD

**Issue by framemytv** [Frame-My-TV/app#165]
When printing a packing slip the page breaks are landing in an odd location.  See this PDF for an example of what we are getting when we print even though the on screen view in the browser appears normal. 

Can you make the page breaks more natural like they are for the invoices? 

[PackingSlipprint.pdf](https://github.com/Frame-My-TV/app/files/191912/PackingSlipprint.pdf)

**Comment by 26nmedia** [comment]
Kevin,

Not sure where this is item #165 is listed but I did see it the other day and put it on my list.     The packing slip print display had a calculation set up for page breaks.    The PDF code using this same page miss read these breaks when dealing with a Config Purchase.   I have removed the breaks when the print page is a PDF.   So it is all set.    see attached.

Take Care,
David Clark Frauenheim
Owner
26 North Media
954-495-8898 (South East)
617-938-3811 (North East)
323-571-9971 (West Coast)
www.26NorthMedia.com
Websites Made Easy

From: framemytv 
Sent: Monday, March 28, 2016 10:44 AM
To: Frame-My-TV/app 
Cc: 26 North Media 
Subject: [app] Packing slip page breaks (#165)

When printing a packing slip the page breaks are landing in an odd location. See this PDF for an example of what we are getting when we print even though the on screen view in the browser appears normal. 

Can you make the page breaks more natural like they are for the invoices? 

PackingSlipprint.pdf

**Comment by framemytv** [comment]
Sorry it appears I accidentally created this ticket under the wrong repository though I did assign it to you. 

I did just check to verify this fix, but the following is a printout of what I get for a packing list. 

[ScannedPrintout.pdf](https://github.com/Frame-My-TV/app/files/199482/ScannedPrintout.pdf)

**Comment by 26nmedia** [comment]
Kevin,

I too verified the fix when I did this... So is this clicking the PRINT or the PDF???     Because I sent you a note saying I fixed the PDF and left the page break calculations that Mike did in place for Printing.     It was these page breaks that were throwing off the packlist when a Configs was purchased.    But it looked fine when I looked at the print on screen??


Maybe it is the header that is throwing off the page calculations IF you had Mike say calculate to NOT break up a configutors attributes.     If so choice at this point REMOVE the header OR break mid config.   

Please advise. 



Take Care,
David Clark Frauenheim
Owner
26 North Media
954-495-8898 (South East)
617-938-3811 (North East)
323-571-9971 (West Coast)
www.26NorthMedia.com
Websites Made Easy

**Comment by framemytv** [comment]
David,

Unfortuantely, I’m not using the print PDF function because it just doesn’t work for me through Safari so I don’t know about that.  With Safari I personally can easily print to PDF, but everyone else here who is on a PC doesn’t have the great print to PDF functionality that is natively a part of MacOSX.  I decided to drop the topic of trying to get PDFs to be an attachment to an email and focus on other topics.

Dane does use the new PDF feature … it’s easier for her than what she was dong previously, but it still extra steaps to download it to here computer then re-attached it

…….

In regards to this specific ticket yes I do recall that Mike did some page breaks for separate configurations … but since the recent changes with creating PDFs and such now anytime we print a packaging slip we just get the address header only on the first page.

Yes, on screen it looks find but when you actually click print that’s were it comes out the way my scanned PDF looked.

Maybe something happened with the formatting because previously a first config would still fit on the page without being broken. It’s was 2nd and 3rd configs that used to be broken up onto multiple pages.

- Kevin


KEVIN HANCOCK / www.FrameMyTV.com<http://www.framemytv.com/>
e:  kevin@framemytv.com<mailto:kevin@framemytv.com>  t:  978.912.7149  f:  978.241.6215    [Connect on LinkedIn] <http://www.linkedin.com/pub/kevin-hancock/32/273/438?trk=shareTw>
[Frame My TV]

[http://framemytv.com/images/generalsiteimages/ExternalReferences/facebook_100.jpg]<http://www.facebook.com/FrameMyTV> [http://framemytv.com/images/generalsiteimages/ExternalReferences/twitter_logo_100.jpg] <http://twitter.com/FrameMyTV>  [http://framemytv.com/images/generalsiteimages/ExternalReferences/pinterest-button_100.png] <http://pinterest.com/framemytv/>
